version: '3.9'
services:
  primary-db:
    image: postgres:14
    container_name: primary_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appointmentDB
    ports:
      - "5432:5432"
    volumes:
      - primary_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redundant-db:
    image: postgres:14
    container_name: redundant_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appointmentDB_redundant
    ports:
      - "5433:5432"
    volumes:
      - redundant_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  primary_data:
  redundant_data:
