version: "3.9"
services:
  primary-db:
    image: postgres:14
    container_name: primary_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appointmentDB
    ports:
      - "5433:5432" # Maps container's 5432 to host's 5433
    volumes:
      - primary_data:/var/lib/postgresql/data
    command: [ "postgres", "-c", "wal_level=logical", "-c", "max_wal_senders=10", "-c", "max_replication_slots=10" ]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d appointmentDB"]
      interval: 10s
      timeout: 5s
      retries: 5

  redundant-db:
    image: postgres:14
    container_name: redundant_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appointmentDB_redundant
    ports:
      - "5434:5432" # Maps container's 5432 to host's 5434
    volumes:
      - redundant_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d appointmentDB_redundant"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  primary_data:
  redundant_data:
