spring:
  application:
    name: gateway-service-test
  main:
    web-application-type: reactive

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: '*'
            allowedHeaders: '*'
      # route to service registry logical name service lookup for stress-test instances
      routes:
        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/api/appointments/**

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

        - id: dentist-service-test
          uri: lb://dentist-service-test
          predicates:
            - Path=/api/dentists/**

        - id: logging-service-test
          uri: lb://logging-service-test
          predicates:
            - Path=/api/logs/**

        - id: monitoring-service-test
          uri: lb://monitoring-service-test
          predicates:
            - Path=/api/metrics/**

        - id: notification-service-test
          uri: lb://notification-service-test
          predicates:
            - Path=/api/notifications/**

        - id: patient-service-test
          uri: lb://patient-service-test
          predicates:
            - Path=/api/patients/**


